fail_fast: false
default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.8
    hooks:
      - id: uv-lock

  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: "v3.6.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2
          - prettier-plugin-toml
          - "@prettier/plugin-xml"
          - prettier-plugin-sh
        args:
          - --plugin=prettier-plugin-toml
          - --plugin=prettier-plugin-sh
        exclude: "(^.idea.*|^CHANGELOG.md)"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "[CHANGELOG.md]"
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pytest
        name: pytest-local
        description: Run pytest in the local virtualenv
        stages: [manual]
        entry: >
          uv run pytest
          --verbose
          --cov
          --cov-report=html --cov-report=term
          --cov-report=xml
          --junitxml=junit.xml
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        verbose: true

      - id: mypy
        name: mypy
        description: Run mypy in the local virtualenv
        entry: >
          uv run mypy src tests
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      - id: pyright
        name: pyright
        description: Run pyright
        entry: pyright
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
